# Generated by Django 3.1.3 on 2020-11-30 08:22

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=30, unique=True, verbose_name='Referencia')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=700, verbose_name='Descripción')),
                ('image1', models.ImageField(blank=True, upload_to='store/item/', verbose_name='Imágen 1')),
                ('image2', models.ImageField(blank=True, upload_to='store/item/', verbose_name='Imágen 2')),
                ('image3', models.ImageField(blank=True, upload_to='store/item/', verbose_name='Imágen 3')),
                ('color1', colorfield.fields.ColorField(blank=True, default='', max_length=18, verbose_name='Color principal')),
                ('color2', colorfield.fields.ColorField(blank=True, default='', max_length=18, verbose_name='Color secundario')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, verbose_name='Peso')),
                ('weight_type', models.CharField(blank=True, help_text='Indique el tipo de medida para el peso indicado (Kg, Lbr, Onz, ...).', max_length=50, verbose_name='Peso (tipo)')),
                ('volumen', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, verbose_name='Volumen')),
                ('volumen_type', models.CharField(blank=True, help_text="Indique el tipo de medida para el volumen indicado (Ejemplo 'metro cúbico').", max_length=50, verbose_name='Volumen (tipo)')),
                ('length_width', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, verbose_name='Longitud de ancho')),
                ('length_height', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, verbose_name='Longitud de alto')),
                ('length_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, verbose_name='Longitud de profundidad')),
                ('length_type', models.CharField(blank=True, help_text="Indique el tipo de medida para las longitudes indicadas (Ejemplo 'metro').", max_length=50, verbose_name='Longitud (tipo)')),
                ('material', models.CharField(blank=True, help_text="Tipo de material principal del cual está constituído (Ejemplo 'plástico').", max_length=50, verbose_name='Material')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, verbose_name='Precio')),
                ('is_active', models.BooleanField(default=True, help_text='El artículo estará o no visible para la venta.', verbose_name='Activo')),
                ('is_featured', models.BooleanField(default=False, help_text='El artículo aparecerá en los primeros lugares de la tienda.', verbose_name='Destacado')),
                ('available', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Disponibles')),
                ('count_search', models.IntegerField(default=0, editable=False, verbose_name='Búsquedas')),
                ('count_views', models.IntegerField(default=0, editable=False, verbose_name='Vistas')),
                ('count_taken', models.IntegerField(default=0, editable=False, verbose_name='Añadidas a la cesta')),
                ('count_sold', models.IntegerField(default=0, editable=False, verbose_name='Ventas')),
                ('tags', models.CharField(blank=True, editable=False, max_length=700)),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['-is_featured', '-available'],
            },
        ),
    ]
