# Generated by Django 3.1.3 on 2020-12-15 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Número')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Modificación')),
                ('create_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creó')),
                ('site', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
                ('update_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario modificó')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
            },
        ),
        migrations.CreateModel(
            name='Mov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField(verbose_name='Cantidad')),
                ('price', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Precio')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Impuestos')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=17, verbose_name='Importe')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=17, verbose_name='Importe')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Modificación')),
                ('create_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mov_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creó')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
                ('update_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mov_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario modificó')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
            },
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('site', 'number'), name='unique_order'),
        ),
    ]
