# Generated by Django 3.1.3 on 2020-12-18 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernote',
            name='create_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordernote_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creó'),
        ),
        migrations.AddField(
            model_name='ordernote',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='create_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creó'),
        ),
        migrations.AddField(
            model_name='order',
            name='site',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
        migrations.AddField(
            model_name='order',
            name='update_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario modificó'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mov',
            name='create_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mov_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creó'),
        ),
        migrations.AddField(
            model_name='mov',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item'),
        ),
        migrations.AddField(
            model_name='mov',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order'),
        ),
        migrations.AddField(
            model_name='mov',
            name='update_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mov_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario modificó'),
        ),
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Marca a la que pertenece.', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.brand', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='item',
            name='group',
            field=models.ManyToManyField(blank=True, help_text='Categoría a la que pertenece.', to='store.Group', verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='item',
            name='site',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
        migrations.AddField(
            model_name='group',
            name='site',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
        migrations.AddField(
            model_name='brand',
            name='site',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('site', 'number'), name='unique_order'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('site', 'codename'), name='unique_item'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('site', 'name'), name='unique_group'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(fields=('site', 'name'), name='unique_brand'),
        ),
    ]
