# Generated by Django 3.1.3 on 2020-12-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True, verbose_name='Capacidad'),
        ),
        migrations.AddField(
            model_name='item',
            name='capacity_type',
            field=models.CharField(blank=True, help_text='El tipo de medida para la capacidad indicada (ejemplos BTU, Watts, Voltios, Amperaje, Hz, etc.', max_length=50, verbose_name='Capacidad (tipo)'),
        ),
    ]
