# Generated by Django 3.1.3 on 2020-12-15 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_auto_20201215_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=700, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, max_length=700, verbose_name='Comentario'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('CREDIT_CARD', 'Tarjeta de crédito'), ('BANK_ACCOUNT', 'Cuenta de banco'), ('OTHER', 'Otro')], default='CASH', max_length=20, verbose_name='Forma de pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfonos'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PROCESS', 'En proceso'), ('COMPLETE', 'Completado')], default='PROCESS', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha del último estado'),
        ),
        migrations.CreateModel(
            name='OrderNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('content', models.CharField(max_length=700, verbose_name='Contenido')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('create_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordernote_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creó')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
            ],
            options={
                'verbose_name': 'Nota de orden',
                'verbose_name_plural': 'Notas de ordenes',
            },
        ),
    ]
