# Generated by Django 3.1.3 on 2020-12-05 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201201_0522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='store/brand/', verbose_name='Imágen')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='store/group/', verbose_name='Imágen')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Marca a la que pertenece.', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.brand', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='item',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Categoría a la que pertenece.', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.group', verbose_name='Grupo'),
        ),
    ]
