# Generated by Django 3.1.3 on 2020-12-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201205_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='group',
        ),
        migrations.AddField(
            model_name='item',
            name='group',
            field=models.ManyToManyField(blank=True, help_text='Categoría a la que pertenece.', null=True, to='store.Group', verbose_name='Grupo'),
        ),
    ]
