# Generated by Django 3.1.3 on 2020-12-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201215_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accepted_policies',
            field=models.BooleanField(default=False, help_text='Al marcar esta casilla usted acepta y está de acuerdo con las políticas del sitio para compras en línea.', verbose_name='Estoy de acuerdo con las políticas del sitio'),
        ),
    ]
