# Generated by Django 3.1.3 on 2020-12-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201220_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesetting',
            name='policies',
            field=models.CharField(blank=True, help_text='Texto que contine una versión corta de las políticas, términos y condiciones de al compara a través de la tienda en línea. Este texto aparecerá en las ordenes impresas que realicen los clientes a través la tienda en línea.', max_length=700, verbose_name='Políticas de la tienda en línea'),
        ),
    ]
