# Generated by Django 3.1.3 on 2020-12-15 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('store', '0005_auto_20201215_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='site',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
    ]
