# Generated by Django 3.1.3 on 2020-11-25 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(help_text='Nombre de este sitio. ', max_length=70, verbose_name='Nombre del sitio')),
                ('icon', models.ImageField(blank=True, help_text='Imagen que aparecerá junto al título en la pestaña del navegador web. Esta imagen debe ser cuadrada, de no serlo se recortará para conseguir la dimensión requerida.', null=True, upload_to='', verbose_name='Icono del sitio')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('description', models.CharField(blank=True, help_text='Breve descripción del sitio.', max_length=200, verbose_name='Descripción')),
                ('cover', models.ImageField(blank=True, help_text='Imagen de portada que se mostraráen la parte superior.', null=True, upload_to='', verbose_name='Portada')),
                ('cover_height', models.IntegerField(default=256, help_text='Altura que tendrá la portada.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(512)], verbose_name='Portada tamaño')),
            ],
            options={
                'verbose_name': 'Ajustes',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_network_name', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Facebook'), ('linkedin', 'LinkedIn'), ('pinterest', 'Pinterest'), ('snapchat', 'Snapchat'), ('telegram', 'Telegram'), ('tumblr', 'Tumblr'), ('twitter', 'Twitter'), ('vkontakte', 'Vkontakte'), ('whatsapp', 'Whatsapp'), ('youtube', 'Youtube')], max_length=20, unique=True, verbose_name='Red social')),
                ('url', models.URLField(help_text='Enlace hacia su perfil en esta red social.', unique=True, verbose_name='URL')),
                ('index', models.IntegerField(default=0, help_text='Ordena los links de las redes sociales acorde a este indice.', validators=[django.core.validators.MinValueValidator(-99), django.core.validators.MaxValueValidator(99)], verbose_name='Indice')),
            ],
            options={
                'verbose_name': 'Red social',
                'verbose_name_plural': 'Redes sociales',
                'ordering': ['index', 'social_network_name'],
            },
        ),
    ]
