# Generated by Django 3.1.3 on 2020-12-21 21:30

import django.contrib.sites.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='advancedsetting',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.models.SiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='brandrepresented',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.models.SiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.models.SiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='sampleimage',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.models.SiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='samplevideo',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.models.SiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='schedule',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.models.SiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='setting',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.models.SiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='slide',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.models.SiteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='socialnetwork',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.models.SiteManager()),
            ],
        ),
    ]
