# Generated by Django 3.1.3 on 2020-11-25 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdvancedSettings',
            new_name='AdvancedSetting',
        ),
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
