# Generated by Django 3.1.3 on 2020-11-26 03:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20201125_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Imagen')),
                ('title', models.CharField(blank=True, max_length=70, verbose_name='Título')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('index', models.IntegerField(default=0, help_text='Orden de las diapositivas.', validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Indice')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Diapositiva',
                'verbose_name_plural': 'Diapositivas',
                'ordering': ['index', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='social_network_name',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('pinterest', 'Pinterest'), ('snapchat', 'Snapchat'), ('telegram', 'Telegram'), ('tumblr', 'Tumblr'), ('twitter', 'Twitter'), ('vkontakte', 'Vkontakte'), ('whatsapp', 'Whatsapp'), ('youtube', 'Youtube')], max_length=20, unique=True, verbose_name='Red social'),
        ),
    ]
