# Generated by Django 3.1.3 on 2020-12-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20201212_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='information_content',
            field=models.TextField(blank=True, default='Póngase en contacto con nostros ahora mismo.', verbose_name='Información: Contenido'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='information_title',
            field=models.CharField(blank=True, default='Póngase en contacto con nostros', max_length=70, verbose_name='Información: Título'),
        ),
    ]
