# Generated by Django 3.1.3 on 2020-12-23 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20201223_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitcounter',
            options={'ordering': ['last_date'], 'verbose_name': 'Visita', 'verbose_name_plural': 'Visitas'},
        ),
        migrations.RenameField(
            model_name='visitcounter',
            old_name='date',
            new_name='last_date',
        ),
        migrations.AddField(
            model_name='visitcounter',
            name='first_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Primer acceso'),
            preserve_default=False,
        ),
    ]
