# Generated by Django 3.1.3 on 2020-11-29 02:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20201126_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.BooleanField(default=True, verbose_name='Lunes')),
                ('monday_ini', models.TimeField(blank=True, default=datetime.time(8, 0), null=True, verbose_name='Lunes: desde')),
                ('monday_end', models.TimeField(blank=True, default=datetime.time(18, 0), null=True, verbose_name='Lunes: hasta')),
                ('tuesday', models.BooleanField(default=True, verbose_name='Tuesday')),
                ('tuesday_ini', models.TimeField(blank=True, default=datetime.time(8, 0), null=True, verbose_name='Tuesday: desde')),
                ('tuesday_end', models.TimeField(blank=True, default=datetime.time(18, 0), null=True, verbose_name='Tuesday: hasta')),
                ('wednesday', models.BooleanField(default=True, verbose_name='Wednesday')),
                ('wednesday_ini', models.TimeField(blank=True, default=datetime.time(8, 0), null=True, verbose_name='Wednesday: desde')),
                ('wednesday_end', models.TimeField(blank=True, default=datetime.time(18, 0), null=True, verbose_name='Wednesday: hasta')),
                ('thursday', models.BooleanField(default=True, verbose_name='Thursday')),
                ('thursday_ini', models.TimeField(blank=True, default=datetime.time(8, 0), null=True, verbose_name='Thursday: desde')),
                ('thursday_end', models.TimeField(blank=True, default=datetime.time(18, 0), null=True, verbose_name='Thursday: hasta')),
                ('friday', models.BooleanField(default=True, verbose_name='Friday')),
                ('friday_ini', models.TimeField(blank=True, default=datetime.time(8, 0), null=True, verbose_name='Friday: desde')),
                ('friday_end', models.TimeField(blank=True, default=datetime.time(18, 0), null=True, verbose_name='Friday: hasta')),
                ('saturday', models.BooleanField(default=True, verbose_name='Saturday')),
                ('saturday_ini', models.TimeField(blank=True, default=datetime.time(8, 0), null=True, verbose_name='Saturday: desde')),
                ('saturday_end', models.TimeField(blank=True, default=datetime.time(18, 0), null=True, verbose_name='Saturday: hasta')),
                ('sunday', models.BooleanField(default=False, verbose_name='Sunday')),
                ('sunday_ini', models.TimeField(blank=True, default=datetime.time(8, 0), null=True, verbose_name='Sunday: desde')),
                ('sunday_end', models.TimeField(blank=True, default=datetime.time(18, 0), null=True, verbose_name='Sunday: hasta')),
            ],
            options={
                'verbose_name': 'Horario de servicio',
                'verbose_name_plural': 'Horario de servicio',
            },
        ),
    ]
