# Generated by Django 3.1.3 on 2020-12-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20201223_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitcounter',
            options={'ordering': ['date'], 'verbose_name': 'Visita', 'verbose_name_plural': 'Visitas'},
        ),
        migrations.RemoveField(
            model_name='visitcounter',
            name='first_date',
        ),
        migrations.RemoveField(
            model_name='visitcounter',
            name='last_date',
        ),
        migrations.AddField(
            model_name='visitcounter',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Último acceso'),
        ),
        migrations.AddConstraint(
            model_name='visitcounter',
            constraint=models.UniqueConstraint(fields=('site', 'urlpath', 'date'), name='unique_visitcounter'),
        ),
    ]
