# Generated by Django 3.1.3 on 2020-11-29 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='address',
            field=models.CharField(blank=True, max_length=256, verbose_name='Dirección principal'),
        ),
        migrations.AddField(
            model_name='setting',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='setting',
            name='phone1',
            field=models.CharField(blank=True, max_length=20, verbose_name='Central telefónica'),
        ),
        migrations.AddField(
            model_name='setting',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Central telefónica'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='saturday_end',
            field=models.TimeField(blank=True, default=datetime.time(12, 0), null=True, verbose_name='Saturday: hasta'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sunday_end',
            field=models.TimeField(blank=True, default=datetime.time(12, 0), null=True, verbose_name='Sunday: hasta'),
        ),
    ]
