# Generated by Django 3.1.3 on 2021-02-09 22:33

import base.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20201223_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='teléfono')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='dirección')),
                ('service_type', models.CharField(blank=True, max_length=100, verbose_name='servicio')),
                ('warranty', models.CharField(blank=True, max_length=100, verbose_name='garantía')),
                ('message', models.CharField(blank=True, max_length=700, verbose_name='mensaje')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('read_date', models.DateTimeField(blank=True, null=True, verbose_name='fecha de leído')),
            ],
            options={
                'verbose_name': 'mensaje',
                'verbose_name_plural': 'mensajes',
                'ordering': ['-date', 'email'],
            },
        ),
        migrations.AlterModelOptions(
            name='advancedsetting',
            options={'verbose_name': 'configuración avanzada', 'verbose_name_plural': 'configuración avanzada'},
        ),
        migrations.AlterModelOptions(
            name='brandrepresented',
            options={'ordering': ['index'], 'verbose_name': 'marca', 'verbose_name_plural': 'marcas'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'pregunta', 'verbose_name_plural': 'preguntas'},
        ),
        migrations.AlterModelOptions(
            name='sampleimage',
            options={'ordering': ['index'], 'verbose_name': 'imagen de muestra', 'verbose_name_plural': 'imágenes de muestra'},
        ),
        migrations.AlterModelOptions(
            name='samplevideo',
            options={'ordering': ['index'], 'verbose_name': 'video de muestra', 'verbose_name_plural': 'videos de muestra'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'horario de servicio', 'verbose_name_plural': 'horario de servicio'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['index', 'id'], 'verbose_name': 'diapositiva', 'verbose_name_plural': 'diapositivas'},
        ),
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'ordering': ['index', 'social_network_name'], 'verbose_name': 'red social', 'verbose_name_plural': 'redes sociales'},
        ),
        migrations.AlterModelOptions(
            name='visitcounter',
            options={'ordering': ['date'], 'verbose_name': 'visita', 'verbose_name_plural': 'visitas'},
        ),
        migrations.AlterField(
            model_name='brandrepresented',
            name='cover',
            field=models.ImageField(blank=True, help_text='imagen que se usará como fondo para ambientar la sección de la marca. Se recomienda una imagen en alta resolución, con dimensión rectangular más ancha que alta.', upload_to='brand', verbose_name='portada'),
        ),
        migrations.AlterField(
            model_name='brandrepresented',
            name='image',
            field=models.ImageField(help_text='logo de la marca. Se recomienda una imagen cuadrada, con fondo transparente, en formato PNG o GIF.', upload_to='brand', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='brandrepresented',
            name='index',
            field=models.IntegerField(default=0, help_text='determina la posición que ocupará la marca cuando se muestre junto a las demás. Las marcas se mostrarán en orden en función de su indice, de mejor a mayor.', verbose_name='indice'),
        ),
        migrations.AlterField(
            model_name='brandrepresented',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='brandrepresented',
            name='url',
            field=models.URLField(blank=True, help_text='dirección URL del sitio web de la marca.', verbose_name='web site'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=700, verbose_name='respuesta'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=100, unique=True, verbose_name='pregunta'),
        ),
        migrations.AlterField(
            model_name='sampleimage',
            name='description',
            field=models.CharField(blank=True, max_length=700, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='sampleimage',
            name='image',
            field=models.ImageField(upload_to='sapleimage', validators=[base.models.validate_image_size], verbose_name='imágen'),
        ),
        migrations.AlterField(
            model_name='sampleimage',
            name='index',
            field=models.IntegerField(default=0, help_text='orden en que será mostrada la imagen con respecto a otra.', verbose_name='indice'),
        ),
        migrations.AlterField(
            model_name='sampleimage',
            name='title',
            field=models.CharField(blank=True, max_length=70, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='samplevideo',
            name='description',
            field=models.CharField(blank=True, max_length=700, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='samplevideo',
            name='index',
            field=models.IntegerField(default=0, help_text='orden en que será mostrado el video con respecto a otro.', verbose_name='indice'),
        ),
        migrations.AlterField(
            model_name='samplevideo',
            name='title',
            field=models.CharField(blank=True, max_length=70, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='samplevideo',
            name='video',
            field=models.FileField(upload_to='saplevideo', validators=[base.models.validate_video_size], verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(upload_to='slide', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='index',
            field=models.IntegerField(default=0, help_text='orden de las diapositivas.', validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='indice'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activa'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='title',
            field=models.CharField(blank=True, max_length=70, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='index',
            field=models.IntegerField(default=0, help_text='ordena los links de las redes sociales acorde a este indice.', validators=[django.core.validators.MinValueValidator(-99), django.core.validators.MaxValueValidator(99)], verbose_name='indice'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='social_network_name',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('pinterest', 'Pinterest'), ('snapchat', 'Snapchat'), ('telegram', 'Telegram'), ('tumblr', 'Tumblr'), ('twitter', 'Twitter'), ('vkontakte', 'Vkontakte'), ('whatsapp', 'Whatsapp'), ('youtube', 'Youtube')], max_length=20, verbose_name='red social'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='url',
            field=models.URLField(help_text='enlace hacia su perfil en esta red social.', unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='visitcounter',
            name='count',
            field=models.IntegerField(default=0, verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='visitcounter',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='fecha'),
        ),
    ]
