# Generated by Django 3.1.3 on 2020-11-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20201129_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('image', models.ImageField(upload_to='brand', verbose_name='Imagen')),
                ('index', models.IntegerField(default=0, verbose_name='Indice')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['index'],
            },
        ),
        migrations.AlterField(
            model_name='setting',
            name='cover',
            field=models.ImageField(blank=True, help_text='Imagen de portada que se mostraráen la parte superior.', null=True, upload_to='setting', verbose_name='Portada'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='icon',
            field=models.ImageField(blank=True, help_text='Imagen que aparecerá junto al título en la pestaña del navegador web. Esta imagen debe ser cuadrada, de no serlo se recortará para conseguir la dimensión requerida.', null=True, upload_to='setting', verbose_name='Icono del sitio'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='setting', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono secundario'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(upload_to='slide', verbose_name='Imagen'),
        ),
    ]
