# Generated by Django 3.1.3 on 2020-11-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20201129_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='about_content',
            field=models.TextField(blank=True, verbose_name='Contenido'),
        ),
        migrations.AddField(
            model_name='setting',
            name='about_image_cover',
            field=models.ImageField(blank=True, upload_to='about', verbose_name='Portada'),
        ),
        migrations.AddField(
            model_name='setting',
            name='about_image_footer',
            field=models.ImageField(blank=True, upload_to='about', verbose_name='Imagen pie de página'),
        ),
        migrations.AddField(
            model_name='setting',
            name='about_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='Título'),
        ),
    ]
