# Generated by Django 3.1.3 on 2020-11-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20201129_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='about_content',
            field=models.TextField(blank=True, verbose_name='Acerca de: Contenido'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='about_image_cover',
            field=models.ImageField(blank=True, upload_to='about', verbose_name='Acerca de: Portada'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='about_image_footer',
            field=models.ImageField(blank=True, upload_to='about', verbose_name='Acerca de: Imagen pie de página'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='about_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='Acerca de: Título'),
        ),
    ]
