# Generated by Django 3.1.3 on 2020-11-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20201130_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='cover',
            field=models.ImageField(blank=True, help_text='Imagen que se usará como fondo para ambientar la sección de la marca. Se recomienda una imagen en alta resolución, con dimensión rectangular más ancha que alta.', upload_to='brand', verbose_name='Portada'),
        ),
        migrations.AddField(
            model_name='brand',
            name='url',
            field=models.URLField(blank=True, help_text='Dirección URL del sitio web de la marca.', verbose_name='Web Site'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(help_text='Logo de la marca. Se recomienda una imagen cuadrada, con fondo transparente, en formato PNG o GIF.', upload_to='brand', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='index',
            field=models.IntegerField(default=0, help_text='Determina la posición que ocupará la marca cuando se muestre junto a las demás. Las marcas se mostrarán en orden en función de su indice, de mejor a mayor.', verbose_name='Indice'),
        ),
    ]
