# Generated by Django 3.1.3 on 2020-12-02 23:43

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=70, verbose_name='Título')),
                ('description', models.CharField(blank=True, max_length=700, verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='sapleimage', verbose_name='Imágen')),
                ('index', models.IntegerField(default=0, help_text='Orden en que será mostrada la imagen con respecto a otra.', verbose_name='Indice')),
            ],
            options={
                'verbose_name': 'Imagen de muestra',
                'verbose_name_plural': 'Imágenes de muestra',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='SampleVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=70, verbose_name='Título')),
                ('description', models.CharField(blank=True, max_length=700, verbose_name='Descripción')),
                ('video', models.FileField(upload_to='saplevideo', validators=[base.models.validate_video_size], verbose_name='Video')),
                ('index', models.IntegerField(default=0, help_text='Orden en que será mostrado el video con respecto a otro.', verbose_name='Indice')),
            ],
            options={
                'verbose_name': 'Video de muestra',
                'verbose_name_plural': 'Videos de muestra',
                'ordering': ['index'],
            },
        ),
    ]
