# Generated by Django 3.1.3 on 2020-12-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20201203_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='embed_promo_url',
            field=models.URLField(blank=True, help_text='URL del contenido externo que desea mostrar como promoción en la página principal. Esta url puede bien ser la url de un video en Youtube, una imagen, o un contenido html.', verbose_name='URL de promoción incrustrada'),
        ),
    ]
