# Generated by Django 3.1.3 on 2020-12-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_setting_embed_promo_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Ajustes', 'verbose_name_plural': 'Ajustes'},
        ),
        migrations.AddField(
            model_name='setting',
            name='embed_map_url',
            field=models.URLField(blank=True, help_text='URL de la dirección de la empresa en Google Maps.', verbose_name='URL de Google Maps'),
        ),
        migrations.AddField(
            model_name='setting',
            name='schedule',
            field=models.CharField(blank=True, max_length=150, verbose_name='Horario de trabajo'),
        ),
    ]
