# Generated by Django 3.1.3 on 2020-12-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20201208_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='embed_map_url',
        ),
        migrations.AddField(
            model_name='setting',
            name='embed_map_html',
            field=models.TextField(blank=True, help_text='Código HTML/Javascript que se mostrará en una de las partes de la página principal.', verbose_name='Código inserción 1'),
        ),
    ]
