# Generated by Django 3.1.3 on 2020-12-18 11:27

import django.contrib.sites.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('user', '0002_auto_20201218_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone1',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono principal'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono secundario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='site',
            field=models.ForeignKey(default=django.contrib.sites.models.SiteManager.get_current, editable=False, on_delete=django.db.models.deletion.PROTECT, to='sites.site'),
        ),
    ]
