# Generated by Django 3.1.3 on 2020-12-15 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201212_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=700, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='profile',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Perfil activo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone1',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono principal'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono secundario'),
        ),
    ]
