# Generated by Django 3.1.3 on 2020-12-15 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('user', '0003_auto_20201215_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='site',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.PROTECT, to='sites.site'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
