# Generated by Django 3.1.3 on 2020-12-18 17:28

import django.contrib.sites.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('user', '0003_auto_20201218_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_userid',
            field=models.CharField(blank=True, editable=False, max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='Imagen de perfil desde URL'),
        ),
        migrations.AlterField(
            model_name='user',
            name='site',
            field=models.ForeignKey(default=django.contrib.sites.models.SiteManager.get_current, editable=False, on_delete=django.db.models.deletion.PROTECT, to='sites.site'),
        ),
    ]
