# Generated by Django 3.1.3 on 2020-12-18 19:00

import django.contrib.sites.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('user', '0004_auto_20201218_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='initial_password',
            field=models.CharField(blank=True, max_length=10, verbose_name='Contraseña inicial establecida por el sistema'),
        ),
        migrations.AlterField(
            model_name='user',
            name='site',
            field=models.ForeignKey(default=django.contrib.sites.models.SiteManager.get_current, editable=False, on_delete=django.db.models.deletion.PROTECT, to='sites.site'),
        ),
    ]
