# Generated by Django 3.1.3 on 2020-12-21 21:30

import django.contrib.sites.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('user', '0006_auto_20201220_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='site',
            field=models.ForeignKey(default=django.contrib.sites.models.SiteManager.get_current, editable=False, on_delete=django.db.models.deletion.PROTECT, to='sites.site'),
        ),
    ]
